name: 'ci-vue3-template'
on:
  push:
    paths:
      - 'packages/cli/templates/vue3/**'
      - 'packages/field-plugin/**'
jobs:
  check-if-releasing-library:
    uses: ./.github/workflows/check-if-releasing-library.yml
  test-and-build:
    needs: check-if-releasing-library
    if: ${{ needs.check-if-releasing-library.outputs.result == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install
      - name: Build the template
        run: yarn workspace field-plugin-vue3-template build
      - name: Unit Tests
        run: yarn workspace field-plugin-vue3-template test
