name: 'test-test'
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: 'yarn'
      - run: echo "${{ github.event.pull_request.title }}"
      - run: echo "${{ !startsWith(github.event.pull_request.title, 'chore(lib): release @storyblok/field-plugin@') }}"
